org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.251
neo_version_range=[21.1,)
loader_version_range=[1,)

mod_id=universal_tool
mod_name=Universal Tool
mod_license=MIT
mod_version=1.0.0
mod_group_id=org.gwfx.universaltool
mod_authors=Zuo_yan
mod_description=All-in-one universal tools combining pickaxe, axe, shovel, hoe and sword for Minecraft 1.21.1 NeoForge.
